### ISSUE TITLE
qtl_effects not working properly on data generated using QTLpoly2 functions

### ISSUE THREAD

**Issue by jeekinlau** [gabrielgesteira/QTLpoly#11]
Hi Gabriel,

I found that the qtl_effects() function, does not work with objects generated from fit_model2(). Attached is a picture of the plot the warnings and the allele effect plots which are super funky. 

![image](https://github.com/user-attachments/assets/8b72d35f-2a28-4145-b3c3-e014d26a8e5e)

**Comment by gabrielgesteira** [comment]
Hi @jeekinlau, thanks for letting us know about this issue. This is also due to changes in the mappoly2 object structures. It should be an easy fix, I am working on it and will pull a fixed function soon.

**Comment by gabrielgesteira** [comment]
This issue should be solved with the latest changes (more specifically commit 0e2bbf3cb70cf3f1892d8bb312d46e0225dd5fb7). Thanks again for pointing this out @jeekinlau
