### ISSUE TITLE
importing diploid data not working

### ISSUE THREAD

**Issue by jeekinlau** [gabrielgesteira/QTLpoly#4]
when importing diploid data for read_data() not working error below... has to probably do with line  and following lines 
https://github.com/gabrielgesteira/QTLpoly/blob/58f5cfdd39ee00215525f178db6fde93e9ffd57c/R/read_data.R#L116

```
Error in apply(Pgametes[which(lapply(Punique, length) >= n.unique), ],  : 
  dim(X) must have a positive length
```

**Comment by gabrielgesteira** [comment]
Hi Jeekin, thanks for letting me know. I have a branch with a simple fix for diploid datasets. Please give it a try:

`devtools::install_github("gabrielgesteira/QTLpoly",ref="diploid_fix")`
`library(qtlpoly)`

I created this branch months ago but haven´t merged it into the main branch yet. Please let me know if that works for your dataset.

Thanks!

Gabriel

**Comment by jeekinlau** [comment]
yes the diploid set runs with maps generated from a .csv dosage files... i havent tried vcf generated diploid yet. i dont think that would be an issue
