### ISSUE TITLE
testing null_model2

### ISSUE THREAD

**Issue by jeekinlau** [gabrielgesteira/QTLpoly#5]
so i am testing null_model2 and maybe there is a bug... not sure if it is a bug or if it just wont work with missing data

if i run this line
`data.sim = simulate_qtl(data = data, mu = 0, h2.qtl = NULL, var.error = 1, n.sim = 1000, missing = T, seed = 1234) `
`score.null = null_model2(data = data.sim$results, n.clusters = 2, plot = NULL)`
then i get an error 
Error in { : 
  task 1 failed - "NA/NaN/Inf in foreign function call (arg 1)"

if i run missing =F it runs fine

**Comment by gabrielgesteira** [comment]
Thanks for letting me know @jeekinlau, I will work on it soon!

**Comment by gabrielgesteira** [comment]
@jeekinlau This should be fixed after 205d38bce172342e478c2047c0071788cc991a4c
Please reopen if you find any errors. Thank you!

**Comment by gabrielgesteira** [comment]
Closing this issue.
