### ISSUE TITLE
Conversion not working

### ISSUE THREAD

**Issue by jeekinlau** [gabrielgesteira/QTLpoly#9]
https://github.com/gabrielgesteira/QTLpoly/blob/2578b3570bd3653521b7e1d712039296820b72f7/R/read_data2.R#L72C1-L85C5

Hi Gabriel,

I am trying to help Ivan with some qtl mapping with maps made in mappoly2. However looks as if this is the issue. Marcelo must have made changes to the file structure of the mappoly2.sequence object. My suggestion is that this read_data2 function needs also another argument for whether genome, mds, or custom map should be used. I tried for a little bit to try to fix the function but it is too complicated for my brain. 

Best,

Jeekin

**Comment by jeekinlau** [comment]
should be working now once the pull request is merged. please double check my code, I may be rusty with mappoly2 datastructures

**Comment by gabrielgesteira** [comment]
Hi @jeekinlau, thanks for pointing this out and working on fixing it. This issue and #11 occurred after changes in the mappoly2 object structures. I am still testing the proposed changes before merging to the main branch. For reference, the mentioned pull request is #10.

**Comment by gabrielgesteira** [comment]
All tests passed, so #10 is now merged to the main branch.
